// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsYsp7S4Qax65SzQs3JjwZjsNZKW3QV9I',
    appId: '1:854607500232:web:2536a977526b80e0fb66fd',
    messagingSenderId: '854607500232',
    projectId: 'mobilesflutter2024-80b96',
    authDomain: 'mobilesflutter2024-80b96.firebaseapp.com',
    storageBucket: 'mobilesflutter2024-80b96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5sppoJS7ZGp25yvXssulJI10O7jVFkQ',
    appId: '1:854607500232:android:2fea1cdc73813fb4fb66fd',
    messagingSenderId: '854607500232',
    projectId: 'mobilesflutter2024-80b96',
    storageBucket: 'mobilesflutter2024-80b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYNX5M1MjZlfNmGgpni2wHOldOvOW3fdU',
    appId: '1:854607500232:ios:cae045b4dadd9881fb66fd',
    messagingSenderId: '854607500232',
    projectId: 'mobilesflutter2024-80b96',
    storageBucket: 'mobilesflutter2024-80b96.appspot.com',
    iosBundleId: 'com.example.progmsn2024',
  );

}